### PR TITLE
Final changes

### PR DESCRIPTION
**Pull request by nullpixel**

### CODE REVIEW

**Comment by nullpixel** [comment]
[If user is not logged into the feedback website, bot should send a link to the website and ask them to do so](https://trello.com/c/EWU0dVg8/31-if-user-is-not-logged-into-the-feedback-website-bot-should-send-a-link-to-the-website-and-ask-them-to-do-so)

**Comment by nullpixel** [comment]
[Descriptive errors for incorrect commands](https://trello.com/c/gfIRGpiq/18-descriptive-errors-for-incorrect-commands)

**Comment by nullpixel** [comment]
[!search function](https://trello.com/c/WJbF7QIe/3-search-function)

**Comment by nullpixel1** [comment]
[!search function](https://trello.com/c/WJbF7QIe/3-search-function)

**Comment by nullpixel** [comment]
[Whenever the bot responds to a specific command, it should @mention the user that issued the command.](https://trello.com/c/ExkP1jCW/19-whenever-the-bot-responds-to-a-specific-command-it-should-mention-the-user-that-issued-the-command)

**Pull request merged**
