### PR TITLE
Remove year and race conditions from !stats (Request)

### PR DESCRIPTION
**Pull request by LW001**

### CODE REVIEW

**Comment by Dougley** [comment]
I like the year being present in the stats command, is there a good reason to not show it anymore?

**Comment by LW001** [comment]
Well you do know what year the days of the last week were

**Review by Dougley — DISMISSED** [review]

**Comment by Dougley** [comment]
Please resolve your merge conflicts

**Comment by nullpixel** [comment]
resolved for him

**Review by Dougley — APPROVED** [review]

**Pull request merged**
