### PR TITLE
Log UV responses to bot-error

### PR DESCRIPTION
**Pull request by Arzte**
For some reason big merges aren't happening, could be affecting smaller ones too, have yet to see.

### CODE REVIEW

**Comment by Dougley** [comment]
GitHub pls, @SirDoctors seems like GitHub fucked up merging the latest commits into your branch automatically, could you rebase manually and check if the diff is still correct?

**Comment by Arzte** [comment]
I'll rebase it, then remove your GitHub merge commit (since it'd be redundant with the rebase)

**Comment by Arzte** [comment]
done.

**Comment by Dougley** [comment]
Please fix your style issues and I'll merge this 👍

**Review by nullpixel — CHANGES_REQUESTED** [review]
run eslint . --fix

**Comment by Arzte** [comment]
Yeah, that's what I did, guess I need to run the older version of it that travis is using ATM.

**Comment by Arzte** [comment]
Travis errors weren't mine it seems, following a merge from master into this branch it worked just fine. Should be good for merging.

**Review by nullpixel — APPROVED** [review]

**Pull request merged**
