### PR TITLE
Complete Command

### PR DESCRIPTION
**Pull request by RSNFreud**
This is the basis of the complete command. Do not merge yet as it has a few issues which need to be ironed out. Any feedback would be appreciated.

Command works same way as delete did, use the !complete with id and reason, gets sent to admin feed and then has to be approved. (Problem currently is that once its approved in feed it doesnt actually change status but working on it)

### CODE REVIEW

**Comment by Dougley** [comment]
🍿

**Comment by LW001** [comment]
indent more pls
image

**Comment by RSNFreud** [comment]
im crying.. someone save me.. it doesnt like it when i copy code over...

**Review by Dougley — CHANGES_REQUESTED** [review]
IDs for emotes are wrong.
Why do we need this?

**Comment by RSNFreud** [comment]
Emotes were wrong cause different id on testing server. will fix that now. We need this as there are a lot of suggestions on UV that are done and we cant report them as inappropiate. This way it will let a staff member know and will mark as complete therefore removing it from the feed.

**Comment by RSNFreud** [comment]
Dont merge yet Doug, got an error to sort out from bugsnag.. take a look if you can.

`Error Unhandled promise: Promise {
  <rejected> TypeError: Cannot read property 'loginAs' of undefined
    at CompleteCard.getMail.then.f (C:\Users\\Downloads\DiscordFeedback-master\Commands\Commands\queue.js:643:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:208:7) }: TypeError: Cannot read property 'loginAs' of undefined 
    Commands\Commands\queue.js:643:16 getMail.then.f
    unknown none
    unknown _tickDomainCallback (internal/process/next_tick.js:208:7) }: TypeError: Cannot read property 'loginAs' of
    index.js:105:20 on
    events.js:125:13 emitTwo
    events.js:213:7 emit
    internal/process/promises.js:85:22 emitPendingUnhandledRejections
    internal/process/next_tick.js:209:7 _tickDomainCallback`

**Comment by nullpixel** [comment]
We’re currently discussing the scope to this command. This pull request will not be merged until we have finished the new admin queue.

**Comment by Dougley** [comment]
Aside from being broken (https://github.com/SteamingMutt/DiscordFeedback/pull/50#issuecomment-313404363), this doesn't fit our vision for the next version of the admin queue.

**Pull request closed without merging**
