### PR TITLE
Fix autorole

### PR DESCRIPTION
**Pull request by ThaTiemsz**
😀

### CODE REVIEW

**Comment by nullpixel** [comment]
this does not fix it. the for const actually made it work.

**Comment by ThaTiemsz** [comment]
🤔 are you certain? The `return` statements in the for loop end the loop, which is why it only looped through a couple of users

**Comment by nullpixel** [comment]
that's why we use continue?

**Comment by ThaTiemsz** [comment]
Reverted back to the for loop

**Comment by ThaTiemsz** [comment]
Reverted back to the for loop

**Review by nullpixel — APPROVED** [review]

**Pull request merged**
