### PR TITLE
Allowing any whitespace character to be used between dupe links

### PR DESCRIPTION
**Pull request by LW001**
I need this for copying stuff over from other sites, you can now use newlines, tabs, etc

### CODE REVIEW

**Comment by RSNFreud** [comment]
LWWarez:TM:

**Comment by LW001** [comment]
LWWarez:tm:

**Comment by Dougley** [comment]
I'll test tomorrow and get back to you.

**Comment by Arzte** [comment]
16 days ago

**Comment by ThaTiemsz** [comment]
26 days ago

**Comment by LW001** [comment]
Nearing the 30 days, what time do you live in tho

**Comment by LW001** [comment]
One month hype 🎉

**Comment by LW001** [comment]
@SteamingMutt wake up its the next day

**Review by Dougley — CHANGES_REQUESTED** [review]
`TypeError: Cannot read property 'match' of undefined`

**Comment by LW001** [comment]
who even cares about this lol

**Comment by ThaTiemsz** [comment]
@LW001 You did

**Pull request closed without merging**
