### PR TITLE
add feature to use previously used link (with "-")

### PR DESCRIPTION
**Pull request by brxxn**
in the pinned messages, you said you wanted it. felt like it was an easy task, tell me if i did something wrong.

note: untested

### CODE REVIEW

**Comment by LW001** [comment]
Fix travis please

**Comment by Dougley** [comment]
Since you're targeting `develop`, you don't have to worry too much about Travis. (However, if you do, it's appreciated!)

**Comment by brxxn** [comment]
Internet went out, can’t fix.

- mobile

**Comment by brxxn** [comment]
(And going to another country for 2 weeks)

**Comment by Arzte** [comment]
The travis error is caused by access_checker, which would be fixed by #44. (and as stated in that pr, its a temp fix for a later rewrite)

**Comment by Arzte** [comment]
Alright, this should be good for merging

**Review by Dougley — APPROVED** [review]
Did a quick change to ensure this was working.

**Comment by Dougley** [comment]
[Quickly report multiple cards as duplicate of a previous report](https://trello.com/c/eNerz2SK/62-quickly-report-multiple-cards-as-duplicate-of-a-previous-report)

**Pull request merged**
