### PR TITLE
Update way to get next rank in stats command

### PR DESCRIPTION
**Pull request by ThaTiemsz**
Hopefully this works without any problems 😨 

This fixes the "Days needed for next rank" for members who have some roles, but their streak reset _cough LW cough_

### CODE REVIEW

**Comment by LW001** [comment]
Does that mean I won't get librarian in one day

**Comment by ThaTiemsz** [comment]
@LW001 yes

**Comment by LW001** [comment]
You're dead to me

**Review by Dougley — APPROVED** [review]
Directly inconveniencing LW? Sign me the fuck up.

**Pull request merged**
